BK7258_BOARD_SCHEMA=1
BK7258_BOARD_NAME=t5ai_core
BK7258_BOARD_CP_CONFIG=boards/bk7258/t5ai_core/configs/app
BK7258_BOARD_AP_CONFIG=boards/bk7258/t5ai_core/configs/openvela_ap
BK7258_BOARD_PARTITION=boards/bk7258/common/partitions/bk7258/bk7258_ab_onchip_persistent.csv
BK7258_BOARD_RELEASE_POLICY=boards/bk7258/common/release/bk7258_product.release.csv
