#!/usr/bin/env python3
"""Materialize a safe, entity-local BK7258 source snapshot.

The BK7258 executor has to build against a private view of the source tree.
This module owns only that source-view preparation step.  It deliberately
does not invoke a compiler, a packer, a signer, or hardware tooling.

The source checkout is copied by walking the filesystem rather than by using
``git archive``.  That is important for the contest tree: a dirty board
change and an ignored-but-required OpenAMP source file are both build inputs.
Only relative symlinks whose final target is inside the snapshot may survive.
Every copied regular file is a new inode and the completed tree is made
read-only.  Bootloader outputs are intentionally excluded; a role staging
step must copy the bootloader inputs/outputs to a separate writable area.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator, Mapping


ROOTS = (
    "nuttx",
    "apps",
    "external",
    "frameworks",
    "packages",
    "prebuilts",
    "vendor",
    "contest2026_135_yongwangzhiqian",
)

# Public aliases make the scope easy for a caller to inspect without parsing
# the manifest.  Keep these names stable: the scope is part of the identity
# contract, not an incidental implementation detail.
REQUIRED_ROOTS = ROOTS
SOURCE_ROOTS = ROOTS

SCHEMA = "bk7258.entity-source-snapshot/1"
KIND = "entity-source-snapshot-manifest"
VERSION = 1
MANIFEST_FILENAME = "bk7258-source-snapshot.json"
SNAPSHOT_MANIFEST = MANIFEST_FILENAME
REQUIREMENTS_MARKER_FILENAME = "SNAPSHOT-REQUIRED.json"


class SnapshotError(RuntimeError):
    """Raised when a source or destination cannot be snapshotted safely."""


# VCS metadata is never a build input.  ``.git`` is commonly a symlink in a
# repo-manifest checkout, so it must be excluded before symlink validation.
VCS_NAMES = frozenset({
    ".git",
    ".gitmodules",
    ".gitattributes",
    ".git-annex",
    ".repo",
    ".gitignore",
    ".hg",
    ".bzr",
    ".svn",
    "CVS",
    "_darcs",
})

PYTHON_CACHE_NAMES = frozenset({
    "__pycache__",
    ".cache",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".nox",
})

# Build output directories occur in several third-party trees.  A source
# directory with one of these names is not an input to an entity build.
BUILD_DIR_NAMES = frozenset({
    "CMakeFiles",
    "cmake_out",
    "cmake-build",
})

# A basename such as ``build`` or ``out`` is also used by real third-party
# source projects.  Keep those trees unless a path is a known generated
# workspace output or has a strong CMake marker.  This exact list includes the
# board test output that is present in the contest checkout.
KNOWN_GENERATED_DIR_PATHS = frozenset({
    "nuttx/staging",
    "contest2026_135_yongwangzhiqian/board/bk7258/tests/build",
    "contest2026_135_yongwangzhiqian/tools/windows-hardware-debug/ble-gatt-client/out",
    "contest2026_135_yongwangzhiqian/tools/windows-hardware-debug/ble-advertiser/out",
})

NUTTX_GENERATED_DIR_PREFIXES = frozenset({
    # The checked-out workspace contains prior BK7258 build/probe output in
    # these directories.  They are not NuttX source inputs.
    "nuttx/staging",
})
NUTTX_GENERATED_DIR_NAME_PREFIXES = ("bk7258-",)
NUTTX_BUILD_OUTPUT_SUFFIXES = frozenset({
    ".o",
    ".a",
    ".elf",
    ".map",
    ".su",
    ".dep",
    ".d",
    ".bin",
    ".hex",
})

BUILD_OUTPUT_DIR_NAMES = frozenset({"build", "out", "_build"})
BUILD_OUTPUT_FILE_SUFFIXES = frozenset({
    ".o",
    ".a",
    ".elf",
    ".map",
    ".su",
    ".dep",
    ".d",
})
STRONG_BUILD_MARKERS = frozenset({
    "CMakeCache.txt",
    "CMakeFiles",
    "cmake_install.cmake",
    "CTestTestfile.cmake",
    "build.ninja",
    ".ninja_deps",
    ".ninja_log",
    "compile_commands.json",
})

BUILD_FILE_NAMES = frozenset({
    "CMakeCache.txt",
    "cmake_install.cmake",
    "CTestTestfile.cmake",
    "build.ninja",
    "compile_commands.json",
    ".ninja_deps",
    ".ninja_log",
})

# These paths are generated by the shared NuttX configure/build flow.  They
# are excluded as paths (rather than inspected as links) because in a normal
# checkout they are absolute links back into the shared workspace.
GENERATED_LINK_PATHS = frozenset({
    "nuttx/Make.defs",
    "nuttx/arch/arm/include/board",
    "nuttx/arch/arm/include/chip",
    "nuttx/arch/arm/src/board",
    "nuttx/arch/arm/src/chip",
    # The following three are also generated configure links in the openvela
    # workspace.  They are not source roots and retaining them would either
    # expose the checkout or recreate a shared source view.
    "nuttx/include/arch",
    "nuttx/drivers/platform",
    "apps/platform/board",
})

# These links are repository metadata or optional upstream source aliases,
# not BK7258 build inputs.  They are excluded only when the entry itself is a
# symlink; a real source file with one of these names is retained.
OPTIONAL_METADATA_SYMLINK_NAMES = frozenset({
    ".clang-format",
    ".dockerignore",
    "rustfmt.toml",
})
OPTIONAL_MISSING_SYMLINK_PATHS = frozenset({
    # This aggregation entry points to an optional top-level tests checkout,
    # which is absent in the openvela workspace.
    "apps/tests",
    # PCRE2's generated chartable source is optional for the BK products
    # (CONFIG_LIB_PCRE2 is disabled); do not retain a dangling link.
    "external/pcre2/pcre2_chartables.c",
})

SHARED_NUTTX_FILES = frozenset({
    "nuttx/.config",
    "nuttx/defconfig",
    "nuttx/Make.defs",
    "nuttx/include/nuttx/config.h",
})

# Files generated by the BK7258 BL1/BL2 build and pack flow.  Source C/H/ASM
# and linker/Make files remain in the snapshot; generated objects/images do
# not.  The names are intentionally path-scoped below.
BOOTLOADER_GENERATED_NAMES = frozenset({
    "bootloader.tmp",
    "bl_crc.json",
    "bl2_crc.bin.json",
    "bl_crc.bin",
    "bl2.bin",
    "bl2_crc.bin",
    "bl.elf",
    "bl.bin",
    "bl.map",
    "bl2.elf",
    "bl2.map",
})
BOOTLOADER_GENERATED_SUFFIXES = frozenset({
    ".o",
    ".a",
    ".elf",
    ".bin",
    ".hex",
    ".map",
    ".su",
    ".dep",
})

READ_CHUNK = 1024 * 1024


def _canonical_json(value: Any) -> bytes:
    """Return deterministic JSON bytes for manifest identities."""

    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _inside(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except ValueError:
        return False


def _safe_path(value: Path | str, field_name: str) -> Path:
    if not isinstance(value, (Path, str)):
        raise SnapshotError(f"{field_name} must be a filesystem path")
    path = Path(value).expanduser()
    if "\x00" in str(path):
        raise SnapshotError(f"{field_name} contains NUL")
    return path


def _reject_traversal(path: Path, field_name: str) -> None:
    # The destination is caller-controlled.  Refusing ``..`` components keeps
    # the lexical path and the audited path identical and makes the safety
    # boundary reviewable.  A caller can still name any absolute destination
    # outside the workspace.
    if ".." in path.parts:
        raise SnapshotError(f"{field_name} must not contain '..' traversal")


def _existing_parent_without_symlinks(path: Path, field_name: str) -> None:
    """Reject every existing path component that is a symlink.

    Missing ancestors are allowed and are created later.  Checking all
    existing components is important: resolving only the final parent would
    silently accept ``/tmp/link-to-checkout/new``.
    """

    current = path
    while True:
        if current.is_symlink():
            raise SnapshotError(f"{field_name} parent is a symlink: {current}")
        parent = current.parent
        if parent == current:
            break
        current = parent


def _workspace_path(value: Path | str) -> Path:
    path = _safe_path(value, "workspace_root")
    _reject_traversal(path, "workspace_root")
    if not path.is_absolute():
        path = Path.cwd() / path
    if path.is_symlink() or not path.is_dir():
        raise SnapshotError(f"workspace_root must be a real directory: {path}")
    try:
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise SnapshotError(f"cannot resolve workspace_root: {path}") from error
    if resolved != path.absolute():
        # This catches a symlink in the workspace path itself.  Existing
        # parent symlinks are not a source-tree concern, but rejecting them
        # makes the source boundary unambiguous too.
        raise SnapshotError(f"workspace_root path contains a symlink: {path}")
    return resolved


def _valid_requirements_marker(
    path: Path,
    *,
    allow_materialized: bool = False,
) -> bool:
    """Return whether a caller-prepared source-view marker is safe to keep.

    ``bk7258_isolated_executor.py`` creates this one marker before a later
    materialization step.  It is the sole permitted exception to the
    fresh-absent destination rule.  Do not accept a similarly named arbitrary
    file: the marker must be a regular JSON document with the exact source
    scope and an unmaterialized state.
    """

    if path.is_symlink() or not path.is_file():
        return False
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return False
    if not isinstance(value, Mapping):
        return False
    if (
        value.get("kind") != "entity-source-snapshot-requirement"
        or value.get("version") != 1
        or value.get("scope") != list(ROOTS)
    ):
        return False
    if value.get("materialized") is False:
        return True
    if not allow_materialized or value.get("materialized") is not True:
        return False
    identity = value.get("snapshot_identity_sha256")
    return isinstance(identity, str) and len(identity) == 64 and all(
        character in "0123456789abcdef" for character in identity)


def _destination_path(
    value: Path | str,
    workspace: Path,
    *,
    allow_requirements_marker: bool,
) -> tuple[Path, bool]:
    path = _safe_path(value, "destination")
    _reject_traversal(path, "destination")
    if not path.is_absolute():
        path = Path.cwd() / path
    path = path.absolute()

    _existing_parent_without_symlinks(path.parent, "destination")
    try:
        canonical_parent = path.parent.resolve(strict=False)
    except OSError as error:
        raise SnapshotError(f"cannot resolve destination parent: {path.parent}") from error
    if canonical_parent != path.parent.absolute():
        raise SnapshotError(
            f"destination parent does not resolve lexically (symlinked parent): {path.parent}")
    canonical = canonical_parent / path.name
    if canonical == workspace or _inside(canonical, workspace):
        raise SnapshotError("destination must be outside workspace_root")

    # The destination itself must be new.  A single validated marker is the
    # explicit integration exception for the prepare phase, which pre-creates
    # ``source-snapshot/SNAPSHOT-REQUIRED.json`` before this helper runs.
    marker_allowed = False
    if path.exists() or path.is_symlink():
        if (
            allow_requirements_marker
            and not path.is_symlink()
            and path.is_dir()
            and _valid_requirements_marker(path / REQUIREMENTS_MARKER_FILENAME)
        ):
            try:
                existing = sorted(entry.name for entry in os.scandir(path))
            except OSError as error:
                raise SnapshotError(f"cannot inspect existing destination: {path}") from error
            if existing != [REQUIREMENTS_MARKER_FILENAME]:
                raise SnapshotError(
                    "existing destination may contain only a validated "
                    f"{REQUIREMENTS_MARKER_FILENAME}: {path}")
            marker_allowed = True
        else:
            raise SnapshotError(f"destination must be fresh and absent: {path}")
    else:
        # Create only the requested fresh leaf.  Parent creation is allowed,
        # but it is never destructive and is checked again after creation.
        try:
            path.mkdir(parents=True, exist_ok=False)
        except OSError as error:
            raise SnapshotError(f"cannot create fresh destination: {path}") from error
    if path.is_symlink() or not path.is_dir():
        raise SnapshotError(f"destination did not remain a real directory: {path}")
    _existing_parent_without_symlinks(path, "destination")
    try:
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise SnapshotError(f"cannot resolve destination after creation: {path}") from error
    if resolved == workspace or _inside(resolved, workspace):
        raise SnapshotError("resolved destination escaped outside-workspace boundary")
    return path, marker_allowed


def _required_root_name(relative: str) -> str | None:
    first = relative.split("/", 1)[0]
    return first if first in ROOTS else None


def _bootloader_path(relative: str) -> bool:
    parts = relative.split("/")
    prefix = ("contest2026_135_yongwangzhiqian", "board", "bk7258", "bootloader")
    return len(parts) > len(prefix) and tuple(parts[: len(prefix)]) == prefix


def _nuttx_generated_path(relative: str) -> bool:
    parts = relative.split("/")
    if not parts or parts[0] != "nuttx":
        return False
    if any(
        relative == prefix or relative.startswith(prefix + "/")
        for prefix in NUTTX_GENERATED_DIR_PREFIXES
    ):
        return True
    return len(parts) > 1 and parts[1].startswith(NUTTX_GENERATED_DIR_NAME_PREFIXES)


def _excluded_reason(
    relative: str,
    is_dir: bool,
    source_path: Path | None = None,
    is_symlink: bool = False,
) -> str | None:
    """Return a policy reason for an entry, or ``None`` to retain it."""

    parts = relative.split("/")
    name = parts[-1]
    if any(part in VCS_NAMES for part in parts):
        return "vcs-metadata"
    if any(part in PYTHON_CACHE_NAMES for part in parts):
        return "python-cache"
    if is_symlink and relative in OPTIONAL_MISSING_SYMLINK_PATHS:
        # These paths are excluded only for the current missing-target state.
        # If a future checkout supplies the optional source, the normal strict
        # relative-link validation should apply instead.
        if source_path is None:
            return "optional-missing-source-link"
        try:
            target = os.readlink(source_path)
        except OSError as error:
            raise SnapshotError(f"cannot inspect optional symlink: {source_path}") from error
        if os.path.isabs(target):
            return "optional-missing-source-link"
        target_path = Path(os.path.abspath(os.path.join(source_path.parent, target)))
        if not target_path.exists() and not target_path.is_symlink():
            return "optional-missing-source-link"
    if is_symlink and name in OPTIONAL_METADATA_SYMLINK_NAMES:
        return "optional-metadata-symlink"
    if relative in SHARED_NUTTX_FILES:
        return "shared-nuttx-generated-state"
    if relative in GENERATED_LINK_PATHS:
        return "generated-source-link"
    if _nuttx_generated_path(relative):
        return "cmake-or-build-output"
    if is_dir:
        if (
            name in BUILD_DIR_NAMES
            or name.startswith("cmake-build")
            or relative in KNOWN_GENERATED_DIR_PATHS
        ):
            return "cmake-or-build-output"
        if name in BUILD_OUTPUT_DIR_NAMES and source_path is not None:
            try:
                child_names = {
                    child.name for child in os.scandir(source_path)
                }
            except OSError as error:
                raise SnapshotError(
                    f"cannot inspect candidate build directory: {source_path}") from error
            if child_names & STRONG_BUILD_MARKERS:
                return "cmake-or-build-output"
        return None
    if name.endswith(".pyc"):
        return "python-cache"
    if name in BUILD_FILE_NAMES:
        return "cmake-or-build-output"
    if (
        parts[0] == "nuttx"
        and Path(name).suffix in NUTTX_BUILD_OUTPUT_SUFFIXES
    ):
        return "cmake-or-build-output"
    if (
        Path(name).suffix in BUILD_OUTPUT_FILE_SUFFIXES
        and any(part in BUILD_OUTPUT_DIR_NAMES for part in parts[:-1])
    ):
        return "cmake-or-build-output"
    if _bootloader_path(relative):
        if name in BOOTLOADER_GENERATED_NAMES or Path(name).suffix in BOOTLOADER_GENERATED_SUFFIXES:
            return "bootloader-generated-artifact"
    return None


def _excluded_path(relative: str) -> bool:
    """Check a normalized path as a symlink target.

    Target paths are normalized but not followed by this function.  The
    caller separately resolves the final target to reject links escaping the
    workspace or pointing through another invalid link.
    """

    parts = relative.split("/")
    if any(part in VCS_NAMES or part in PYTHON_CACHE_NAMES for part in parts):
        return True
    if relative in SHARED_NUTTX_FILES:
        return True
    if _nuttx_generated_path(relative):
        return True
    if any(
        relative == generated or relative.startswith(generated + "/")
        for generated in GENERATED_LINK_PATHS
    ):
        return True
    for part in parts:
        if part in BUILD_DIR_NAMES or part.startswith("cmake-build"):
            return True
    if any(
        "/".join(parts[:index + 1]) in KNOWN_GENERATED_DIR_PATHS
        for index in range(len(parts))
    ):
        return True
    if (
        Path(parts[-1]).suffix in BUILD_OUTPUT_FILE_SUFFIXES
        and any(part in BUILD_OUTPUT_DIR_NAMES for part in parts[:-1])
    ):
        return True
    if _bootloader_path(relative):
        name = parts[-1]
        if name in BOOTLOADER_GENERATED_NAMES or Path(name).suffix in BOOTLOADER_GENERATED_SUFFIXES:
            return True
    return False


def _validate_source_symlink(
    source_link: Path,
    workspace: Path,
    relative: str,
) -> str:
    """Validate and return a relative symlink target.

    Absolute links are always rejected, including absolute links that happen
    to point inside the workspace.  A relative link must resolve to an
    existing path inside one of the copied roots and may not resolve through a
    generated/VCS path.
    """

    try:
        target = os.readlink(source_link)
    except OSError as error:
        raise SnapshotError(f"cannot read symlink: {source_link}") from error
    if not target or os.path.isabs(target):
        raise SnapshotError(
            f"only relative in-snapshot symlinks are allowed: {relative} -> {target!r}")

    target_lexical = Path(os.path.abspath(os.path.join(source_link.parent, target)))
    if not _inside(target_lexical, workspace):
        raise SnapshotError(
            f"symlink target escapes workspace_root: {relative} -> {target!r}")
    try:
        target_relative = target_lexical.relative_to(workspace).as_posix()
    except ValueError as error:  # pragma: no cover - covered by _inside above
        raise SnapshotError(f"cannot normalize symlink target: {source_link}") from error
    if _required_root_name(target_relative) is None or _excluded_path(target_relative):
        raise SnapshotError(
            f"symlink target is not an included snapshot path: {relative} -> {target!r}")
    if not target_lexical.exists() and not target_lexical.is_symlink():
        raise SnapshotError(f"dangling symlink is not allowed: {relative} -> {target!r}")
    try:
        resolved = target_lexical.resolve(strict=True)
    except OSError as error:
        raise SnapshotError(
            f"symlink target cannot be resolved: {relative} -> {target!r}") from error
    if not _inside(resolved, workspace):
        raise SnapshotError(
            f"symlink target resolves outside workspace_root: {relative} -> {target!r}")
    try:
        resolved_relative = resolved.relative_to(workspace).as_posix()
    except ValueError as error:  # pragma: no cover - covered by _inside above
        raise SnapshotError(f"cannot normalize resolved symlink target: {source_link}") from error
    if _required_root_name(resolved_relative) is None or _excluded_path(resolved_relative):
        raise SnapshotError(
            f"symlink target resolves to an excluded path: {relative} -> {target!r}")
    return target


@dataclass
class _TreeStats:
    digest: Any = field(default_factory=hashlib.sha256)
    file_count: int = 0
    byte_count: int = 0
    directory_count: int = 0
    symlink_count: int = 0
    hardlink_count: int = 0
    # Exclusions are source-side audit information and are intentionally not
    # part of the tree identity.  A destination has no excluded entries.
    excluded_count: int = 0
    excluded_by_reason: dict[str, int] = field(default_factory=dict)

    def add_directory(self, relative: str) -> None:
        self.directory_count += 1
        self.digest.update(f"dir\0{relative}\n".encode("utf-8"))

    def add_file(self, relative: str, size: int, content_digest: str) -> None:
        self.file_count += 1
        self.byte_count += size
        self.digest.update(
            f"file\0{relative}\0{size}\0{content_digest}\n".encode("utf-8"))

    def add_symlink(self, relative: str, target: str) -> None:
        self.symlink_count += 1
        self.digest.update(f"link\0{relative}\0{target}\n".encode("utf-8"))

    def finish(self) -> str:
        return self.digest.hexdigest()


def _hash_file(path: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    try:
        with path.open("rb") as stream:
            while True:
                chunk = stream.read(READ_CHUNK)
                if not chunk:
                    break
                digest.update(chunk)
                size += len(chunk)
    except OSError as error:
        raise SnapshotError(f"cannot read source file: {path}") from error
    return digest.hexdigest(), size


def _copy_regular_file(source: Path, destination: Path, source_mode: int) -> tuple[str, int]:
    """Copy bytes into a new inode and return its digest and byte count."""

    digest = hashlib.sha256()
    size = 0
    destination.parent.mkdir(parents=True, exist_ok=True)
    source_stream = None
    destination_stream = None
    descriptor = -1
    try:
        source_stream = source.open("rb")
        descriptor = os.open(
            destination,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL,
            0o600,
        )
        destination_stream = os.fdopen(descriptor, "wb")
    except OSError as error:
        try:
            if source_stream is not None:
                source_stream.close()
        except OSError:
            pass
        if destination_stream is None and descriptor >= 0:
            try:
                os.close(descriptor)
            except OSError:
                pass
        raise SnapshotError(f"cannot create snapshot file: {destination}") from error

    try:
        with source_stream, destination_stream:
            while True:
                chunk = source_stream.read(READ_CHUNK)
                if not chunk:
                    break
                destination_stream.write(chunk)
                digest.update(chunk)
                size += len(chunk)
        # Keep executable source files executable while removing all write
        # bits.  setuid/setgid/sticky bits are not source-build inputs.
        os.chmod(destination, stat.S_IMODE(source_mode) & 0o555)
    except OSError as error:
        raise SnapshotError(f"cannot copy source file: {source} -> {destination}") from error
    return digest.hexdigest(), size


def _iter_children(path: Path) -> Iterator[os.DirEntry[str]]:
    try:
        entries = list(os.scandir(path))
    except OSError as error:
        raise SnapshotError(f"cannot inspect source directory: {path}") from error
    yield from sorted(entries, key=lambda entry: entry.name)


def audit_source_symlinks(
    workspace_root: Path | str,
    *,
    raise_on_error: bool = True,
) -> dict[str, Any]:
    """Audit source symlinks without reading or copying regular files.

    The report is useful before a multi-gigabyte snapshot.  Unknown invalid
    links remain fail-closed by default; only the explicit optional metadata
    and source aliases in the policy table are excluded.
    """

    workspace = _workspace_path(workspace_root)
    for root_name in ROOTS:
        root = workspace / root_name
        if root.is_symlink() or not root.is_dir():
            raise SnapshotError(f"required source root is not a real directory: {root}")

    report: dict[str, Any] = {
        "schema": SCHEMA,
        "kind": "entity-source-snapshot-symlink-preflight",
        "version": VERSION,
        "scope": list(ROOTS),
        "bad": [],
        "valid_symlink_count": 0,
        "excluded_symlink_count": 0,
        "excluded_symlinks": [],
        "roots": {},
    }
    for root_name in ROOTS:
        source_root = workspace / root_name
        stack: list[tuple[Path, str]] = [(source_root, root_name)]
        root_report = {
            "valid_symlink_count": 0,
            "excluded_symlink_count": 0,
            "excluded_by_reason": {},
        }
        while stack:
            source_dir, relative_dir = stack.pop()
            for entry in _iter_children(source_dir):
                source_path = Path(entry.path)
                relative = f"{relative_dir}/{entry.name}"
                try:
                    is_link = entry.is_symlink()
                    is_directory = entry.is_dir(follow_symlinks=False)
                    entry.stat(follow_symlinks=False)
                except OSError as error:
                    raise SnapshotError(
                        f"cannot inspect source entry: {source_path}") from error

                reason = _excluded_reason(
                    relative,
                    is_directory and not is_link,
                    source_path,
                    is_link,
                )
                if reason is not None:
                    if is_link:
                        try:
                            target = os.readlink(source_path)
                        except OSError as error:
                            raise SnapshotError(
                                f"cannot read excluded symlink: {source_path}") from error
                        root_report["excluded_symlink_count"] += 1
                        root_report["excluded_by_reason"][reason] = (
                            root_report["excluded_by_reason"].get(reason, 0) + 1)
                        report["excluded_symlink_count"] += 1
                        report["excluded_symlinks"].append({
                            "path": relative,
                            "target": target,
                            "reason": reason,
                        })
                    continue
                if is_link:
                    try:
                        _validate_source_symlink(source_path, workspace, relative)
                    except SnapshotError as error:
                        report["bad"].append({
                            "path": relative,
                            "error": str(error),
                        })
                        if raise_on_error:
                            raise
                    else:
                        root_report["valid_symlink_count"] += 1
                        report["valid_symlink_count"] += 1
                    continue
                if is_directory:
                    stack.append((source_path, relative))
        report["roots"][root_name] = root_report

    report["bad_count"] = len(report["bad"])
    report["excluded_symlinks"].sort(key=lambda item: item["path"])
    for root_report in report["roots"].values():
        root_report["excluded_by_reason"] = dict(
            sorted(root_report["excluded_by_reason"].items()))
    return report


def _walk_source_root(
    source_root: Path,
    destination_root: Path,
    workspace: Path,
    root_name: str,
) -> _TreeStats:
    stats = _TreeStats()
    # Stack entries are real directories.  We never call os.walk with its
    # default followlinks=True and never resolve a source directory through a
    # symlink.
    stack: list[tuple[Path, Path, str]] = [(source_root, destination_root, root_name)]
    while stack:
        source_dir, destination_dir, relative_dir = stack.pop()
        destination_dir.mkdir(parents=True, exist_ok=True)
        for entry in _iter_children(source_dir):
            source_path = Path(entry.path)
            destination_path = destination_dir / entry.name
            relative = f"{relative_dir}/{entry.name}"

            try:
                is_link = entry.is_symlink()
                is_directory = entry.is_dir(follow_symlinks=False)
                source_stat = entry.stat(follow_symlinks=False)
            except OSError as error:
                raise SnapshotError(f"cannot inspect source entry: {source_path}") from error

            reason = _excluded_reason(
                relative,
                is_directory and not is_link,
                source_path,
                is_link,
            )
            if reason is not None:
                stats.excluded_count += 1
                stats.excluded_by_reason[reason] = stats.excluded_by_reason.get(reason, 0) + 1
                continue

            if is_link:
                target = _validate_source_symlink(source_path, workspace, relative)
                if destination_path.exists() or destination_path.is_symlink():
                    raise SnapshotError(f"destination entry already exists: {destination_path}")
                try:
                    destination_path.parent.mkdir(parents=True, exist_ok=True)
                    os.symlink(target, destination_path)
                except OSError as error:
                    raise SnapshotError(
                        f"cannot copy relative symlink: {source_path} -> {destination_path}") from error
                stats.add_symlink(relative, target)
                continue

            if is_directory:
                try:
                    destination_path.mkdir(parents=True, exist_ok=False)
                except FileExistsError as error:
                    raise SnapshotError(f"destination entry already exists: {destination_path}") from error
                except OSError as error:
                    raise SnapshotError(f"cannot create snapshot directory: {destination_path}") from error
                stats.add_directory(relative)
                stack.append((source_path, destination_path, relative))
                continue

            if stat.S_ISREG(source_stat.st_mode):
                # A hard-linked source is deliberately copied as bytes into a
                # fresh inode; no source inode is ever shared with the view.
                if source_stat.st_nlink > 1:
                    stats.hardlink_count += 1
                content_digest, size = _copy_regular_file(
                    source_path, destination_path, source_stat.st_mode)
                stats.add_file(relative, size, content_digest)
                continue

            raise SnapshotError(f"unsupported special source entry: {source_path}")
    return stats


def _walk_snapshot_root(root: Path, root_name: str, destination: Path) -> _TreeStats:
    """Audit one copied root and recompute its tree identity."""

    if root.is_symlink() or not root.is_dir():
        raise SnapshotError(f"snapshot root is not a real directory: {root}")
    stats = _TreeStats()
    stack: list[tuple[Path, str]] = [(root, root_name)]
    while stack:
        current, relative_dir = stack.pop()
        try:
            entries = list(os.scandir(current))
        except OSError as error:
            raise SnapshotError(f"cannot audit snapshot directory: {current}") from error
        for entry in sorted(entries, key=lambda item: item.name):
            path = Path(entry.path)
            relative = f"{relative_dir}/{entry.name}"
            try:
                is_link = entry.is_symlink()
                is_directory = entry.is_dir(follow_symlinks=False)
                item_stat = entry.stat(follow_symlinks=False)
            except OSError as error:
                raise SnapshotError(f"cannot audit snapshot entry: {path}") from error
            if is_link:
                try:
                    target = os.readlink(path)
                except OSError as error:
                    raise SnapshotError(f"cannot read snapshot symlink: {path}") from error
                if not target or os.path.isabs(target):
                    raise SnapshotError(f"snapshot contains unsafe symlink: {relative}")
                target_path = path.parent / target
                try:
                    resolved = target_path.resolve(strict=True)
                except OSError as error:
                    raise SnapshotError(f"snapshot contains dangling symlink: {relative}") from error
                if not _inside(resolved, destination):
                    raise SnapshotError(f"snapshot symlink escapes destination: {relative}")
                stats.add_symlink(relative, target)
                continue
            if is_directory:
                stats.add_directory(relative)
                stack.append((path, relative))
                continue
            if not stat.S_ISREG(item_stat.st_mode):
                raise SnapshotError(f"snapshot contains a special entry: {relative}")
            if item_stat.st_nlink != 1:
                raise SnapshotError(f"snapshot contains a hard-linked file: {relative}")
            if stat.S_IMODE(item_stat.st_mode) & 0o222:
                raise SnapshotError(f"snapshot source file is writable: {relative}")
            content_digest, size = _hash_file(path)
            stats.add_file(relative, size, content_digest)
    return stats


def _set_read_only(root: Path) -> None:
    """Remove write bits from every ordinary source entry in a tree."""

    try:
        entries = list(os.scandir(root))
    except OSError as error:
        raise SnapshotError(f"cannot make snapshot read-only: {root}") from error
    for entry in entries:
        path = Path(entry.path)
        try:
            if entry.is_symlink():
                continue
            if entry.is_dir(follow_symlinks=False):
                _set_read_only(path)
                mode = stat.S_IMODE(entry.stat(follow_symlinks=False).st_mode)
                os.chmod(path, mode & 0o555)
            elif entry.is_file(follow_symlinks=False):
                mode = stat.S_IMODE(entry.stat(follow_symlinks=False).st_mode)
                os.chmod(path, mode & 0o555)
        except OSError as error:
            raise SnapshotError(f"cannot make snapshot entry read-only: {path}") from error
    try:
        mode = stat.S_IMODE(root.stat(follow_symlinks=False).st_mode)
        os.chmod(root, mode & 0o555)
    except OSError as error:
        raise SnapshotError(f"cannot make snapshot root read-only: {root}") from error


def _mark_requirements_materialized(marker_path: Path, identity: str) -> None:
    """Mark a caller-prepared pending marker complete in place.

    The prepare phase owns this marker and intentionally leaves it in the
    source view.  Updating its state avoids a stale ``materialized=false``
    signal without deleting or replacing any path.
    """

    try:
        value = json.loads(marker_path.read_text(encoding="utf-8"))
        mode = stat.S_IMODE(marker_path.stat(follow_symlinks=False).st_mode)
        if not isinstance(value, dict):
            raise ValueError("marker is not an object")
        value["materialized"] = True
        value["snapshot_manifest"] = MANIFEST_FILENAME
        value["snapshot_identity_sha256"] = identity
        # A pre-created marker may already be read-only.  Add only the owner
        # write bit for the in-place update, then restore read-only mode.
        os.chmod(marker_path, mode | stat.S_IWUSR)
        marker_path.write_bytes(_canonical_json(value) + b"\n")
        os.chmod(marker_path, 0o444)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as error:
        raise SnapshotError(
            f"cannot mark snapshot requirements complete: {marker_path}") from error


def _root_summary(stats: _TreeStats) -> dict[str, Any]:
    tree_sha256 = stats.finish()
    return {
        "tree_sha256": tree_sha256,
        # Aliases keep the human-facing contract explicit while allowing
        # callers that use the shorter terminology to consume the manifest.
        "tree_digest": tree_sha256,
        "file_count": stats.file_count,
        "bytes": stats.byte_count,
        "byte_count": stats.byte_count,
        "directory_count": stats.directory_count,
        "symlink_count": stats.symlink_count,
        "source_hardlink_count": stats.hardlink_count,
        "excluded_count": stats.excluded_count,
        "excluded_by_reason": dict(sorted(stats.excluded_by_reason.items())),
    }


def _identity_body(manifest: Mapping[str, Any]) -> dict[str, Any]:
    body = dict(manifest)
    body.pop("identity_sha256", None)
    return body


def manifest_identity(manifest: Mapping[str, Any]) -> str:
    """Compute the overall source identity from a manifest mapping."""

    return _sha256_bytes(_canonical_json(_identity_body(manifest)))


def _audit_top_level(destination: Path, *, requirements_marker: bool = False) -> None:
    allowed = set(ROOTS) | {MANIFEST_FILENAME}
    if requirements_marker:
        allowed.add(REQUIREMENTS_MARKER_FILENAME)
    try:
        entries = list(os.scandir(destination))
    except OSError as error:
        raise SnapshotError(f"cannot inspect snapshot destination: {destination}") from error
    for entry in entries:
        if entry.name not in allowed:
            raise SnapshotError(f"unexpected entry in fresh snapshot: {entry.name}")
        if entry.is_symlink():
            raise SnapshotError(f"snapshot top-level entry must not be a symlink: {entry.name}")


def audit_snapshot(destination: Path | str, manifest: Mapping[str, Any] | None = None) -> dict[str, Any]:
    """Re-audit a materialized snapshot and return its manifest.

    This function is intentionally independent of the copy phase so a later
    role executor can audit a snapshot received from another process before
    using it.
    """

    destination = _safe_path(destination, "destination")
    _reject_traversal(destination, "destination")
    if not destination.is_absolute():
        destination = Path.cwd() / destination
    destination = destination.absolute()
    if destination.is_symlink() or not destination.is_dir():
        raise SnapshotError(f"snapshot destination must be a real directory: {destination}")
    destination = destination.resolve(strict=True)
    manifest_path = destination / MANIFEST_FILENAME
    if manifest is None:
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:
            raise SnapshotError(f"cannot load snapshot manifest: {manifest_path}") from error
    if not isinstance(manifest, Mapping):
        raise SnapshotError("snapshot manifest must be an object")
    supplied_identity = manifest.get("identity_sha256")
    overall_identity = manifest.get("overall_identity_sha256", supplied_identity)
    if not isinstance(supplied_identity, str) or supplied_identity != manifest_identity(manifest):
        raise SnapshotError("snapshot manifest identity_sha256 does not verify")
    if overall_identity != supplied_identity:
        raise SnapshotError("snapshot manifest overall identity does not verify")
    if manifest.get("schema") != SCHEMA or manifest.get("kind") != KIND:
        raise SnapshotError("unsupported BK7258 source snapshot manifest")
    marker_present = (destination / REQUIREMENTS_MARKER_FILENAME).exists()
    if marker_present and not _valid_requirements_marker(
        destination / REQUIREMENTS_MARKER_FILENAME,
        allow_materialized=True,
    ):
        raise SnapshotError("snapshot requirements marker is invalid")
    if marker_present:
        try:
            marker_value = json.loads(
                (destination / REQUIREMENTS_MARKER_FILENAME).read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as error:
            raise SnapshotError("cannot load snapshot requirements marker") from error
        if marker_value.get("materialized") is not True:
            raise SnapshotError("snapshot requirements marker remains pending")
        if marker_value.get("snapshot_identity_sha256") != supplied_identity:
            raise SnapshotError("snapshot requirements marker identity does not verify")
    copy_policy = manifest.get("copy_policy")
    if isinstance(copy_policy, Mapping):
        expected_marker = bool(copy_policy.get("precreated_requirements_marker", False))
        if marker_present != expected_marker:
            raise SnapshotError("snapshot requirements marker presence changed")
    _audit_top_level(destination, requirements_marker=marker_present)
    roots = manifest.get("roots")
    if not isinstance(roots, Mapping) or set(roots.keys()) != set(ROOTS):
        raise SnapshotError("snapshot manifest roots do not match required scope")

    audited_roots: dict[str, Any] = {}
    for root_name in ROOTS:
        root_stats = _walk_snapshot_root(destination / root_name, root_name, destination)
        summary = _root_summary(root_stats)
        if summary["tree_sha256"] != roots[root_name].get("tree_sha256"):
            raise SnapshotError(f"snapshot root digest changed: {root_name}")
        for key in ("file_count", "bytes", "directory_count", "symlink_count"):
            if summary[key] != roots[root_name].get(key):
                raise SnapshotError(f"snapshot root statistics changed: {root_name}.{key}")
        audited_roots[root_name] = summary

    try:
        manifest_mode = stat.S_IMODE(manifest_path.stat(follow_symlinks=False).st_mode)
    except OSError as error:
        raise SnapshotError(f"cannot stat snapshot manifest: {manifest_path}") from error
    if manifest_path.is_symlink() or manifest_mode & 0o222:
        raise SnapshotError("snapshot manifest must be a read-only regular file")
    if marker_present:
        marker_path = destination / REQUIREMENTS_MARKER_FILENAME
        try:
            marker_stat = marker_path.stat(follow_symlinks=False)
        except OSError as error:
            raise SnapshotError(f"cannot stat snapshot requirements marker: {marker_path}") from error
        if not stat.S_ISREG(marker_stat.st_mode) or stat.S_IMODE(marker_stat.st_mode) & 0o222:
            raise SnapshotError("snapshot requirements marker must be read-only")
    return dict(manifest)


def snapshot_workspace(
    workspace_root: Path | str,
    destination: Path | str,
    *,
    allow_requirements_marker: bool = True,
) -> dict[str, Any]:
    """Copy all required source roots to a fresh entity-local destination.

    ``destination`` is created only if it does not exist, and it must resolve
    outside ``workspace_root``.  No existing path is deleted or replaced.
    """

    workspace = _workspace_path(workspace_root)
    for root_name in ROOTS:
        root = workspace / root_name
        if root.is_symlink() or not root.is_dir():
            raise SnapshotError(f"required source root is not a real directory: {root}")

    target, marker_allowed = _destination_path(
        destination,
        workspace,
        allow_requirements_marker=allow_requirements_marker,
    )
    root_summaries: dict[str, dict[str, Any]] = {}
    try:
        for root_name in ROOTS:
            source_root = workspace / root_name
            destination_root = target / root_name
            try:
                destination_root.mkdir(exist_ok=False)
            except OSError as error:
                raise SnapshotError(f"cannot create snapshot root: {destination_root}") from error
            stats = _walk_source_root(
                source_root, destination_root, workspace, root_name)
            root_summaries[root_name] = _root_summary(stats)

        identity_roots = {
            name: {
                key: summary[key]
                for key in (
                    "tree_sha256", "file_count", "bytes", "directory_count",
                    "symlink_count", "excluded_count", "excluded_by_reason",
                )
            }
            for name, summary in root_summaries.items()
        }
        manifest: dict[str, Any] = {
            "schema": SCHEMA,
            "kind": KIND,
            "version": VERSION,
            "scope": list(ROOTS),
            "copy_policy": {
                "method": "filesystem-copy",
                "git_archive": False,
                "dirty_source_included": True,
                "ignored_source_included": True,
                "relative_internal_symlinks": "preserved-and-audited",
                "absolute_symlinks": "rejected",
                "hardlinks": "copied-as-independent-inodes",
                "ordinary_source_read_only": True,
                "precreated_requirements_marker": marker_allowed,
            },
            "excluded_policy": {
                "vcs_metadata": True,
                "python_cache": True,
                "shared_nuttx_config_and_make_defs": sorted(SHARED_NUTTX_FILES),
                "generated_nuttx_links": sorted(GENERATED_LINK_PATHS),
                "cmake_and_build_outputs": True,
                "known_generated_directories": sorted(KNOWN_GENERATED_DIR_PATHS),
                "third_party_build_named_source_directories": "retained-unless-strong-marker",
                "optional_metadata_symlink_names": sorted(OPTIONAL_METADATA_SYMLINK_NAMES),
                "optional_missing_symlink_paths": sorted(OPTIONAL_MISSING_SYMLINK_PATHS),
                "bootloader_generated_artifacts": True,
            },
            "bootloader_policy": {
                "source_inputs_included": True,
                "generated_artifacts_included": False,
                "role_staging_required": True,
                "role_staging_must_be_writable": True,
                "build_invoked": False,
                "signing_invoked": False,
                "hardware_accessed": False,
            },
            "roots": root_summaries,
            "identity_inputs": {
                "scope": list(ROOTS),
                "roots": identity_roots,
                "manifest_format": SCHEMA,
            },
            "manifest_path": MANIFEST_FILENAME,
        }
        identity = manifest_identity(manifest)
        manifest["identity_sha256"] = identity
        manifest_path = target / MANIFEST_FILENAME
        try:
            manifest_path.write_bytes(_canonical_json(manifest) + b"\n")
        except OSError as error:
            raise SnapshotError(f"cannot write snapshot manifest: {manifest_path}") from error

        # The manifest itself is ordinary source metadata and is read-only as
        # well.  Then audit the final result, including every retained link.
        try:
            os.chmod(manifest_path, 0o444)
        except OSError as error:
            raise SnapshotError(f"cannot make snapshot manifest read-only: {manifest_path}") from error
        if marker_allowed:
            _mark_requirements_materialized(
                target / REQUIREMENTS_MARKER_FILENAME,
                identity,
            )
        for root_name in ROOTS:
            _set_read_only(target / root_name)
        audit_snapshot(target, manifest)
        return manifest
    except SnapshotError:
        # Do not remove a partial destination.  Leaving it in place makes a
        # failed attempt observable and preserves the fresh-only guarantee.
        raise


# Friendly aliases for callers that use the operation-oriented name.
create_snapshot = snapshot_workspace
materialize_snapshot = snapshot_workspace
copy_source_snapshot = snapshot_workspace
snapshot = snapshot_workspace
create_source_snapshot = snapshot_workspace
materialize_source_snapshot = snapshot_workspace
preflight_symlinks = audit_source_symlinks


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace-root", "--workspace", dest="workspace_root", required=True,
        type=Path, help="workspace containing the eight required source roots")
    parser.add_argument(
        "--destination", "--dest", dest="destination", required=False,
        type=Path, help="new destination outside the workspace")
    parser.add_argument(
        "--symlink-preflight", action="store_true",
        help="audit source symlinks only; do not create a snapshot")
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    args = _build_parser().parse_args(list(argv) if argv is not None else None)
    try:
        if args.symlink_preflight:
            result = audit_source_symlinks(args.workspace_root)
        else:
            if args.destination is None:
                _build_parser().error(
                    "--destination is required unless --symlink-preflight is used")
            manifest = snapshot_workspace(args.workspace_root, args.destination)
    except SnapshotError as error:
        print(f"bk7258-source-snapshot: ERROR: {error}", file=sys.stderr)
        return 2
    print(json.dumps(
        result if args.symlink_preflight else manifest,
        ensure_ascii=False,
        sort_keys=True,
        indent=2,
    ))
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised by CLI users
    raise SystemExit(main())
