############################################################################
# contest2026_135_yongwangzhiqian/board/bk7258_t5ai/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = bk7258_bringup.c

include $(TOPDIR)/boards/Board.mk
