/* SPDX-License-Identifier: Apache-2.0 */
/* Deterministic host RPC/VFS environment; no target headers or hardware.
 * Compile the two test_bk7258_*_rpc.c entries with an empty NuttX include
 * tree first on the include path (generated by the host Makefile).
 * Hooks run only at explicit unlocked scheduler boundaries.  A blocked
 * worker yields with longjmp after draining every semaphore token.
 */
#ifndef BK7258_SENSOR_RPC_TEST_H
#define BK7258_SENSOR_RPC_TEST_H
#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <setjmp.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <syslog.h>
#include <time.h>
#include <unistd.h>

#define CONFIG_BK7258_APP_MOTION 1
#define CONFIG_BK7258_MOTION_SERVICE 1
#define CONFIG_BK7258_MOTION_DEVPATH "/dev/uorb/sensor_accel0"
#define CONFIG_BK7258_MOTION_RPC_PRIORITY 80
#define CONFIG_BK7258_MOTION_RPC_STACKSIZE 4096
#define CONFIG_BK7258_APP_NFC 1
#define CONFIG_BK7258_NFC_SERVICE 1
#define CONFIG_BK7258_NFC_DEVPATH "/dev/nfc0"
#define CONFIG_BK7258_NFC_RPC_PRIORITY 80
#define CONFIG_BK7258_NFC_RPC_STACKSIZE 4096
#define NXMUTEX_INITIALIZER 0
#define SP_UNLOCKED 0
#define MSEC2TICK(ms) ((clock_t)(ms))
#define RPMSG_ADDR_ANY UINT32_MAX
#define RPMSG_ERR_NO_BUFF (-2002)
#define SNIOC_SET_INTERVAL 1

typedef int mutex_t;
typedef int spinlock_t;
typedef int sem_t;
typedef unsigned int irqstate_t;
struct sensor_accel
{
  uint64_t timestamp;
  float x, y, z;
  int status;
};
struct rpmsg_device { const char *cpu; };
struct rpmsg_endpoint
{
  struct rpmsg_device *rdev;
  void *priv;
  bool ready;
  void (*unbind)(struct rpmsg_endpoint *);
};
typedef int (*ept_cb_t)(struct rpmsg_endpoint *, void *, size_t, uint32_t, void *);
static clock_t ticks;
static jmp_buf worker_idle;
static bool in_worker;
static int callback_depth;
static void (*unlock_hook)(void);
static void (*sleep_hook)(void);
static void (*wait_hook)(void);
static void (*read_hook)(void);
static int (*worker_entry)(int, char **);
static int opens, reads, closes, fd_live, open_error, read_error, close_error;
static int ioctl_error;
static int requests_sent, responses_sent, no_buffers;
static bool drop_reply;
static unsigned int passes;

static void run_hook(void (**slot)(void))
{
  void (*fn)(void) = *slot;
  *slot = NULL;
  if (fn != NULL) fn();
}
static int nxmutex_lock(mutex_t *m) { assert(*m == 0); *m = 1; return 0; }
static int nxmutex_unlock(mutex_t *m)
{
  assert(*m == 1); *m = 0;
  run_hook(&unlock_hook);
  return 0;
}
static irqstate_t spin_lock_irqsave(spinlock_t *m)
{ assert(*m == 0); *m = 1; return 0; }
static void spin_unlock_irqrestore(spinlock_t *m, irqstate_t flags)
{ (void)flags; assert(*m == 1); *m = 0; }
static int nxsem_init(sem_t *s, int shared, unsigned int count)
{ (void)shared; *s = (int)count; return 0; }
static int nxsem_destroy(sem_t *s) { *s = 0; return 0; }
static int nxsem_post(sem_t *s) { (*s)++; return 0; }
static int nxsem_trywait(sem_t *s)
{ if (*s == 0) return -EAGAIN; (*s)--; return 0; }
static int nxsem_wait_uninterruptible(sem_t *s)
{
  assert(in_worker);
  if (*s == 0) longjmp(worker_idle, 1);
  (*s)--;
  return 0;
}
static int nxsem_tickwait_uninterruptible(sem_t *s, clock_t timeout)
{
  run_hook(&wait_hook);
  if (*s != 0) { (*s)--; return 0; }
  ticks += timeout;
  return -ETIMEDOUT;
}
static clock_t clock_systime_ticks(void) { return ticks; }
static int nxsig_usleep(unsigned int us)
{ ticks += (us + 999) / 1000; run_hook(&sleep_hook); return 0; }
static int task_create(const char *name, int pri, int stack,
                       int (*entry)(int, char **), char **args)
{
  (void)name; (void)pri; (void)stack; (void)args;
  worker_entry = entry;
  return 42;
}
static const char *rpmsg_get_cpuname(struct rpmsg_device *d) { return d->cpu; }
static bool is_rpmsg_ept_ready(struct rpmsg_endpoint *e) { return e->ready; }
static int rpmsg_create_ept(struct rpmsg_endpoint *e, struct rpmsg_device *d,
                          const char *name, uint32_t src, uint32_t dest,
                          ept_cb_t cb, void (*unbind)(struct rpmsg_endpoint *))
{
  (void)name; (void)src; (void)dest; (void)cb; (void)unbind;
  e->rdev = d; e->ready = true; e->unbind = unbind;
  return 0;
}
static void rpmsg_destroy_ept(struct rpmsg_endpoint *e) { e->ready = false; }
static int rpmsg_register_callback(void *priv,
   void (*created)(struct rpmsg_device *, void *),
   void (*destroyed)(struct rpmsg_device *, void *),
   bool (*match)(struct rpmsg_device *, void *, const char *, uint32_t),
   void (*bind)(struct rpmsg_device *, void *, const char *, uint32_t))
{ (void)priv; (void)created; (void)destroyed; (void)match; (void)bind; return 0; }
static void rpmsg_unregister_callback(void *priv,
   void (*created)(struct rpmsg_device *, void *),
   void (*destroyed)(struct rpmsg_device *, void *),
   bool (*match)(struct rpmsg_device *, void *, const char *, uint32_t),
   void (*bind)(struct rpmsg_device *, void *, const char *, uint32_t))
{ (void)priv; (void)created; (void)destroyed; (void)match; (void)bind; }
static int rpmsg_trysend(struct rpmsg_endpoint *, const void *, int);
static int mock_open(const char *path, int flags, ...)
{
  (void)path; (void)flags;
  assert(in_worker && !callback_depth && !fd_live);
  opens++;
  if (open_error) { errno = open_error; return -1; }
  fd_live = 1;
  return 42;
}
static ssize_t mock_read(int fd, void *buffer, size_t size)
{
  assert(in_worker && !callback_depth && fd_live && fd == 42);
  reads++;
  run_hook(&read_hook);
  if (read_error) { errno = read_error; return -1; }
  if (size == sizeof(struct sensor_accel))
    {
      struct sensor_accel sample = { 123456, 1.25f, -2.5f, 9.80665f, 0 };
      memcpy(buffer, &sample, size);
    }
  else { assert(size == 1); *(char *)buffer = 1; }
  return (ssize_t)size;
}
static int mock_close(int fd)
{
  assert(in_worker && !callback_depth && fd_live && fd == 42);
  fd_live = 0; closes++;
  if (close_error) { errno = close_error; return -1; }
  return 0;
}
static int mock_ioctl(int fd, unsigned long cmd, ...)
{
  assert(in_worker && !callback_depth && fd_live && fd == 42);
  assert(cmd == SNIOC_SET_INTERVAL);
  if (ioctl_error) { errno = ioctl_error; return -1; }
  return 0;
}
static void mock_syslog(int pri, const char *format, ...)
{ (void)pri; (void)format; }
#define open mock_open
#define read mock_read
#define close mock_close
#define ioctl mock_ioctl
#define syslog mock_syslog
#endif
